import Navigation from "@/components/navigation/Navigation";
import "./globals.css";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body>
        <header>
          <Navigation/>
        </header>
          {children}
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
